window.APP_SEED_CONFIG = Object.freeze({
  appName: 'Semilla App Web',
  backendUrl: String(window.APP_RUNTIME_CONFIG?.backendUrl || '').trim(),
  versionEndpoint: './version.json',
  serviceWorkerPath: './sw.js',

  // Superpoder opcional. Si el bloque P2P_sin_ no existe, la carga dinámica falla
  // de forma controlada y toda la aplicación continúa usando memoriaBACKEND.
  sinBACKEND: window.APP_RUNTIME_CONFIG?.sinBACKEND === true,

  // Sin polling: los eventos de ciclo de vida solo disparan una comprobación.
  // La interfaz únicamente puede recargarse si version.json confirma un deploy nuevo.
  periodicUpdateChecksEnabled: false,
  updateCheckIntervalMs: 0,
  updateCheckOnFocus: true,
  updateCheckOnOnline: true,
  updateCheckOnPageShow: true,
  // Las señales de ciclo de vida se agrupan para que focus/visible/pageshow no
  // conviertan la comprobación de releases en tráfico HTTP repetitivo.
  passiveUpdateCheckMinIntervalMs: 300000,
  startupUpdateCheckDedupMs: 15000,

  // Evita que varias pestañas instaladas hagan la misma consulta al servidor.
  // El sello de última revisión complementa el lock transitorio para impedir que
  // pestañas que arrancan una detrás de otra repitan version.json tras liberarse el lock.
  multiTabCoordinationEnabled: true,
  leaderLockTtlMs: 45000,
  broadcastChannelName: String(window.APP_SEED_METADATA?.cacheNamespace || 'semilla-appweb-pwa') + ':updates',

  // Modo recomendado para esta semilla: aplica cambios sin pedir interacción.
  autoReloadWhenVersionChanges: true,
  autoReloadDelayMs: 700,
  minimumSecondsBetweenAutoReloads: 10,
  showUpdateStatus: true,

  // Escala: el manifiesto público trae huellas ya calculadas. El cliente no descarga
  // todos los archivos críticos en cada revisión.
  releaseManifestAssetsEnabled: true,

  // El Service Worker del release nuevo reutiliza por SHA-256 el shell anterior y
  // descarga solo diferencias. La precarga desde la página queda desactivada para no
  // duplicar esas mismas respuestas; puede habilitarse explícitamente si otro host lo requiere.
  prefetchReleaseAssetsOnCheck: false,
  prefetchReleaseAssetsMax: 120,

  // Diagnóstico opcional contra mutaciones fuera del pipeline de deploy. Aunque se
  // habilite, sus huellas nunca autorizan una recarga automática de la interfaz.
  directFingerprintFallbackEnabled: false,
  directFingerprintFallbackIntervalMs: 300000,
  directFingerprintCheckFiles: [
      './index.html',
      './manifest.webmanifest',
      './textX/languages.json',
      './textX/app/es.json',
      './textX/seo/es.json',
      './textX/app/ar.json',
      './textX/seo/ar.json',
      './textX/app/en.json',
      './textX/seo/en.json',
      './src/css/app.css',
      './src/js/app-metadata.js',
      './src/js/runtime-config.js',
      './src/js/config.js',
      './src/js/application-scope.js',
      './src/js/api.js',
      './src/js/firebase-auth.js',
      './src/js/p2p-storage.js',
      './src/js/p2p-durability.js',
      './src/js/p2p-crypto.js',
      './src/js/p2p-tab-coordinator.js',
      './src/js/p2p-client.js',
      './src/js/p2p-permissions.js',
      './src/js/p2p-space-creation-intent.js',
      './src/js/p2p-invitation-intent.js',
      './src/js/p2p-invitation-audit.js',
      './src/js/project-domain.js',
      './src/js/device-management.js',
      './src/js/i18n.js',
      './src/js/asset-loader.js',
      './src/js/pwa-update-manager.js',
      './src/js/app.js',
      './P2P_sin_RED_LOCALx/P2P_sin_transport.js',
      './assets/ui/ui_logo_principal_96x96.png',
      './assets/notifications/notification_icon_192x192.png',
      './assets/notifications/notification_badge_monochrome_96x96.png',
      './assets/browser/browser_favicon_16x16.png',
      './assets/browser/browser_favicon_32x32.png',
      './assets/apple/apple_touch_icon_152x152.png',
      './assets/apple/apple_touch_icon_180x180.png',
      './assets/pwa/pwa_launcher_any_48x48.png',
      './assets/pwa/pwa_launcher_any_72x72.png',
      './assets/pwa/pwa_launcher_any_96x96.png',
      './assets/pwa/pwa_launcher_any_128x128.png',
      './assets/pwa/pwa_launcher_any_144x144.png',
      './assets/pwa/pwa_launcher_any_192x192.png',
      './assets/pwa/pwa_launcher_any_384x384.png',
      './assets/pwa/pwa_launcher_any_512x512.png',
      './assets/pwa/pwa_launcher_maskable_192x192.png',
      './assets/pwa/pwa_launcher_maskable_512x512.png',
      './assets/browser/browser_favicon_16x16.png.txt',
      './assets/browser/browser_favicon_32x32.png.txt',
      './assets/apple/apple_touch_icon_152x152.png.txt',
      './assets/apple/apple_touch_icon_180x180.png.txt',
      './assets/ui/ui_logo_principal_96x96.png.txt',
      './assets/notifications/notification_icon_192x192.png.txt',
      './assets/notifications/notification_badge_monochrome_96x96.png.txt',
      './assets/pwa/pwa_launcher_any_48x48.png.txt',
      './assets/pwa/pwa_launcher_any_72x72.png.txt',
      './assets/pwa/pwa_launcher_any_96x96.png.txt',
      './assets/pwa/pwa_launcher_any_128x128.png.txt',
      './assets/pwa/pwa_launcher_any_144x144.png.txt',
      './assets/pwa/pwa_launcher_any_192x192.png.txt',
      './assets/pwa/pwa_launcher_any_384x384.png.txt',
      './assets/pwa/pwa_launcher_any_512x512.png.txt',
      './assets/pwa/pwa_launcher_maskable_192x192.png.txt',
      './assets/pwa/pwa_launcher_maskable_512x512.png.txt'
    ],

  // Compatibilidad con la versión anterior del manager.
  fingerprintCheckEnabled: false,
  fingerprintCheckFiles: [
      './index.html',
      './manifest.webmanifest',
      './textX/languages.json',
      './textX/app/es.json',
      './textX/seo/es.json',
      './textX/app/ar.json',
      './textX/seo/ar.json',
      './textX/app/en.json',
      './textX/seo/en.json',
      './src/css/app.css',
      './src/js/app-metadata.js',
      './src/js/runtime-config.js',
      './src/js/config.js',
      './src/js/application-scope.js',
      './src/js/api.js',
      './src/js/firebase-auth.js',
      './src/js/p2p-storage.js',
      './src/js/p2p-durability.js',
      './src/js/p2p-crypto.js',
      './src/js/p2p-tab-coordinator.js',
      './src/js/p2p-client.js',
      './src/js/p2p-permissions.js',
      './src/js/p2p-space-creation-intent.js',
      './src/js/p2p-invitation-intent.js',
      './src/js/p2p-invitation-audit.js',
      './src/js/project-domain.js',
      './src/js/device-management.js',
      './src/js/i18n.js',
      './src/js/asset-loader.js',
      './src/js/pwa-update-manager.js',
      './src/js/app.js',
      './P2P_sin_RED_LOCALx/P2P_sin_transport.js',
      './assets/ui/ui_logo_principal_96x96.png',
      './assets/notifications/notification_icon_192x192.png',
      './assets/notifications/notification_badge_monochrome_96x96.png',
      './assets/browser/browser_favicon_16x16.png',
      './assets/browser/browser_favicon_32x32.png',
      './assets/apple/apple_touch_icon_152x152.png',
      './assets/apple/apple_touch_icon_180x180.png',
      './assets/pwa/pwa_launcher_any_48x48.png',
      './assets/pwa/pwa_launcher_any_72x72.png',
      './assets/pwa/pwa_launcher_any_96x96.png',
      './assets/pwa/pwa_launcher_any_128x128.png',
      './assets/pwa/pwa_launcher_any_144x144.png',
      './assets/pwa/pwa_launcher_any_192x192.png',
      './assets/pwa/pwa_launcher_any_384x384.png',
      './assets/pwa/pwa_launcher_any_512x512.png',
      './assets/pwa/pwa_launcher_maskable_192x192.png',
      './assets/pwa/pwa_launcher_maskable_512x512.png',
      './assets/browser/browser_favicon_16x16.png.txt',
      './assets/browser/browser_favicon_32x32.png.txt',
      './assets/apple/apple_touch_icon_152x152.png.txt',
      './assets/apple/apple_touch_icon_180x180.png.txt',
      './assets/ui/ui_logo_principal_96x96.png.txt',
      './assets/notifications/notification_icon_192x192.png.txt',
      './assets/notifications/notification_badge_monochrome_96x96.png.txt',
      './assets/pwa/pwa_launcher_any_48x48.png.txt',
      './assets/pwa/pwa_launcher_any_72x72.png.txt',
      './assets/pwa/pwa_launcher_any_96x96.png.txt',
      './assets/pwa/pwa_launcher_any_128x128.png.txt',
      './assets/pwa/pwa_launcher_any_144x144.png.txt',
      './assets/pwa/pwa_launcher_any_192x192.png.txt',
      './assets/pwa/pwa_launcher_any_384x384.png.txt',
      './assets/pwa/pwa_launcher_any_512x512.png.txt',
      './assets/pwa/pwa_launcher_maskable_192x192.png.txt',
      './assets/pwa/pwa_launcher_maskable_512x512.png.txt'
    ],

  // Rutas que normalmente no deben cachearse cuando conectes APIs reales.
  networkOnlyPathPrefixes: (window.APP_SEED_METADATA && window.APP_SEED_METADATA.networkOnlyPathPrefixes) || [
    '/api/',
    '/auth/',
    '/admin/api/',
    '/graphql',
    '/webhooks/'
  ]
});
